### PR TITLE
Refactorings:

### PR DESCRIPTION
**Pull request by ramonsmits**
- Needed to supply Useragent
- using cookie container
- CodeVerifier random string also using uppercase range for stronger security
- demo/test using proper async/await
- disposing of responses
- using c# 8 syntax for cleaner code

### CODE REVIEW

**Comment by tomhollander** [comment]
Thanks for the PR @ramonsmits - however it isn't working for me. The HTTP request is hanging on step 1.
Are you able to successfully authenticate?

**Review by tomhollander — CHANGES_REQUESTED** [review]
Thanks - code is much cleaner than before. However, it doesn't seem to work with the latest changes to Tesla's WAF. I pushed some updates in my last commit (https://github.com/tomhollander/TeslaAuth/commit/533dab6a4b749ddbb23495b75051bf995aa8ae1e) - can you please update your branch to incorporate the same changes?

**Comment by ramonsmits** [comment]
I'll check today. Pretty sure it worked and heard my car honk :-).

Thing is that I made these changes because it wasn't working for me. My account has 2FA enabled.

**Comment by tomhollander** [comment]
I've got 2FA on too. Your branch definitely wasn't working when I tested it, although Tesla seem to be changing things rapidly so it's entirely possible it worked at the time. My changes are pretty minimal so it shouldn't be too hard to merge them into your branch. Originally it seemed that each call required different headers, but it seems they are all pretty consistent so we could probably centralise the code to set up the `HttpClient`.

**Comment by ramonsmits** [comment]
Depends on #9 which is already included in this branch.

**Pull request merged**
