### PR TITLE
Added configuration for Nuget packaging

### PR DESCRIPTION
**Pull request by ramonsmits**
I took the liberty to publish a 1.0.0 preview to Nuget https://www.nuget.org/packages/TeslaAuth

### CODE REVIEW

**Comment by tomhollander** [comment]
Thanks @ramonsmits! This was on my list, but happy you beat me to it!

**Comment by ramonsmits** [comment]
@tomhollander DO you have a nuget userid? If so, then I'll add it as an owner to the package on NuGet.

**Comment by tomhollander** [comment]
Yep, `tomhollander`. Thanks!

**Comment by tomhollander** [comment]
Hi @ramonsmits , a quick reminder about this. I need to update package and I'm still not an owner. Thanks!

**Comment by ramonsmits** [comment]
@tomhollander I've added you

**Pull request merged**
